#ifndef EVENTS_H
#define EVENTS_H

enum Events
{
  EV_SELECTCONSOLE,
  EV_CHANGECONSOLEPRESSED,
  EV_STARTCONSOLE,
  EV_STOPCONSOLE,
  EV_TOUCHEDSTANDBYSCREEN,
  EV_ADDCONSOLEPRESSED,
  EV_ADDCONSOLECONFIRM,
  EV_REMOVECONSOLEPRESSED
};

#endif